### ISSUE TITLE
Error using the component

### ISSUE THREAD

**Issue by tejadong** [ryaa/ionic3-multi-level-select#2]
Hello, im trying to use the component. I have follow your steps in readme.MD but im getting a error...

Uncaught (in promise): error: No component factory found for MultiLevelSelectDialogComponent. Did you add it to @NgModule.entryComponents?

I have tried to insert the module in the app.module.ts but i can not because y im use the IonicPage() decorators then y need to define it in the module page.

Im getting the error when i touch the control on the UI.

Any suggestion?

**Comment by ryaa** [comment]
This seems to be related to lazy loading approach that you are using. I will take a look asap and let you know.

**Comment by tejadong** [comment]
Ok, thx

**Comment by ryaa** [comment]
I released the new build 0.0.3 with some changes. Please try it and let me know if this works for you.
Please note that I added the demo project at github and stackblitz - see details here https://github.com/ryaa/ionic3-multi-level-select#demo

**Comment by tejadong** [comment]
Ok i notify you when i try it. Thx
